/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/session": {
    get: operations["show_session"];
    post: operations["create_session"];
    delete: operations["destroy_session"];
  };
  "/api/visits": {
    get: operations["index_visits"];
  };
  "/api/visits/{id}": {
    get: operations["show_visit"];
  };
  "/api/visits/{id}/rank": {
    get: operations["visit_rank"];
  };
  "/api/visits.csv": {
    get: operations["list_visit_csv"];
  };
  "/api/visits/{visit_id}/notes": {
    post: operations["create_visit_note"];
  };
  "/api/visits/{visit_id}/notes/{id}": {
    put: operations["update_visit_note"];
    delete: operations["destroy_visit_note"];
  };
  "/api/visit_sets/{visit_set_id}/notes": {
    post: operations["create_visit_set_note"];
  };
  "/api/visit_sets/{visit_set_id}/notes/{id}": {
    put: operations["update_visit_set_note"];
    delete: operations["destroy_visit_set_note"];
  };
  "/api/mcs_data/{frame_id}.png": {
    get: operations["show_mcs_data_chart"];
  };
  "/api/pfs_designs": {
    get: operations["list_pfs_design"];
  };
  "/api/pfs_designs.png": {
    get: operations["pfs_design_chart"];
  };
  "/api/pfs_designs/{id_hex}.fits": {
    get: operations["download_design"];
  };
  "/api/pfs_designs/{id_hex}": {
    get: operations["show_design"];
  };
  "/api/fits/visits/{visit_id}/sps/{camera_id}.fits": {
    get: operations["show_sps_fits"];
  };
  "/api/fits/visits/{visit_id}/sps/{camera_id}.png": {
    get: operations["show_sps_fits_preview"];
  };
  "/api/fits/visits/{visit_id}/agc/{exposure_id}.fits": {
    get: operations["show_agc_fits"];
  };
  "/api/fits/visits/{visit_id}/mcs/{frame_id}.fits": {
    get: operations["show_mcs_fits"];
  };
  "/api/fits/visits/{visit_id}/mcs/{frame_id}.png": {
    get: operations["show_mcs_fits_preview"];
  };
  "/api/fits/visits/{visit_id}/agc/{exposure_id}-{hdu_index}.png": {
    get: operations["show_agc_fits_preview"];
  };
  "/api/fits/visits/{visit_id}/{exposure_type}/{fits_id}/meta": {
    get: operations["show_fits_meta"];
  };
  "/api/attachments": {
    get: operations["list_attachment"];
    post: operations["create_attachment"];
  };
  "/api/attachments/{account_name}/{file_id}": {
    get: operations["show_attachment"];
  };
  "/api/attachments/{file_id}": {
    delete: operations["destroy_attachment"];
  };
  "/api/healthz": {
    get: operations["healthz"];
  };
}

export interface components {
  schemas: {
    /** AgcExposure */
    AgcExposure: {
      /** Id */
      id: number;
      /** Exptime */
      exptime?: number;
      /** Altitude */
      altitude?: number;
      /** Azimuth */
      azimuth?: number;
      /** Insrot */
      insrot?: number;
      /** Adc Pa */
      adc_pa?: number;
      /** M2 Pos3 */
      m2_pos3?: number;
      /** Outside Temperature */
      outside_temperature?: number;
      /** Outside Pressure */
      outside_pressure?: number;
      /** Outside Humidity */
      outside_humidity?: number;
      /** Measurement Algorithm */
      measurement_algorithm?: string;
      /** Version Actor */
      version_actor?: string;
      /** Version Instdata */
      version_instdata?: string;
      /**
       * Taken At
       * Format: date-time
       */
      taken_at?: string;
      guide_offset?: components["schemas"]["AgcGuideOffset"];
    };
    /** AgcGuideOffset */
    AgcGuideOffset: {
      /** Ra */
      ra?: number;
      /** Dec */
      dec?: number;
      /** Pa */
      pa?: number;
      /** Delta Ra */
      delta_ra?: number;
      /** Delta Dec */
      delta_dec?: number;
      /** Delta Insrot */
      delta_insrot?: number;
      /** Delta Az */
      delta_az?: number;
      /** Delta El */
      delta_el?: number;
      /** Delta Z */
      delta_z?: number;
      /** Delta Z1 */
      delta_z1?: number;
      /** Delta Z2 */
      delta_z2?: number;
      /** Delta Z3 */
      delta_z3?: number;
      /** Delta Z4 */
      delta_z4?: number;
      /** Delta Z5 */
      delta_z5?: number;
      /** Delta Z6 */
      delta_z6?: number;
    };
    /** AgcVisit */
    AgcVisit: {
      /** Exposures */
      exposures: components["schemas"]["AgcExposure"][];
    };
    /** AttachmentEntry */
    AttachmentEntry: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Account Name */
      account_name: string;
      /** Media Type */
      media_type: string;
      /** Exists */
      exists: boolean;
    };
    /** AttachmentList */
    AttachmentList: {
      /** Count */
      count: number;
      /** Entries */
      entries: components["schemas"]["AttachmentEntry"][];
    };
    /** Body_create_attachment_api_attachments_post */
    Body_create_attachment_api_attachments_post: {
      /**
       * File
       * Format: binary
       */
      file: string;
    };
    /** CreateAttachmentResponse */
    CreateAttachmentResponse: {
      /** Path */
      path: string;
    };
    /** CurrentUser */
    CurrentUser: {
      /** Id */
      id: number;
      /** Account Name */
      account_name: string;
    };
    /** DesignData */
    DesignData: {
      /** Fiberid */
      fiberId: number[];
      /** Catid */
      catId: number[];
      /** Tract */
      tract: number[];
      /** Patch */
      patch: string[];
      /** Objid */
      objId: number[];
      /** Ra */
      ra: number[];
      /** Dec */
      dec: number[];
      /** Targettype */
      targetType: number[];
      /** Fiberstatus */
      fiberStatus: number[];
      /** Pfinominal */
      pfiNominal: number[][];
    };
    /** DesignRows */
    DesignRows: {
      /** Science */
      science: number;
      /** Sky */
      sky: number;
      /** Fluxstd */
      fluxstd: number;
      /** Unassigned */
      unassigned: number;
      /** Engineering */
      engineering: number;
      /** Sunss Imaging */
      sunss_imaging: number;
      /** Sunss Diffuse */
      sunss_diffuse: number;
    };
    /** FitsHdu */
    FitsHdu: {
      /** Index */
      index: number;
      header: components["schemas"]["FitsHeader"];
    };
    /** FitsHeader */
    FitsHeader: {
      /** Cards */
      cards: [string, unknown, string][];
    };
    /** FitsMeta */
    FitsMeta: {
      /** Filename */
      filename: string;
      /** Hdul */
      hdul: components["schemas"]["FitsHdu"][];
    };
    /**
     * FitsType
     * @description An enumeration.
     * @enum {string}
     */
    FitsType: "raw" | "calexp";
    /** GuidestarData */
    GuidestarData: {
      /** Ra */
      ra: number[];
      /** Dec */
      dec: number[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** IicSequence */
    IicSequence: {
      /** Visit Set Id */
      visit_set_id: number;
      /** Sequence Type */
      sequence_type?: string;
      /** Name */
      name?: string;
      /** Comments */
      comments?: string;
      /** Cmd Str */
      cmd_str?: string;
      status?: components["schemas"]["IicSequenceStatus"];
      /** Notes */
      notes: components["schemas"]["VisitSetNote"][];
    };
    /** IicSequenceStatus */
    IicSequenceStatus: {
      /** Visit Set Id */
      visit_set_id: number;
      /** Status Flag */
      status_flag?: number;
      /** Cmd Output */
      cmd_output?: string;
    };
    /** McsExposure */
    McsExposure: {
      /** Frame Id */
      frame_id: number;
      /** Exptime */
      exptime?: number;
      /** Altitude */
      altitude?: number;
      /** Azimuth */
      azimuth?: number;
      /** Insrot */
      insrot?: number;
      /** Adc Pa */
      adc_pa?: number;
      /** Dome Temperature */
      dome_temperature?: number;
      /** Dome Pressure */
      dome_pressure?: number;
      /** Dome Humidity */
      dome_humidity?: number;
      /** Outside Temperature */
      outside_temperature?: number;
      /** Outside Pressure */
      outside_pressure?: number;
      /** Outside Humidity */
      outside_humidity?: number;
      /** Mcs Cover Temperature */
      mcs_cover_temperature?: number;
      /** Mcs M1 Temperature */
      mcs_m1_temperature?: number;
      /**
       * Taken At
       * Format: date-time
       */
      taken_at: string;
      /** Notes */
      notes: components["schemas"]["McsExposureNote"][];
    };
    /** McsExposureNote */
    McsExposureNote: {
      /** Id */
      id: number;
      /** Body */
      body: string;
      user: components["schemas"]["ObslogUser"];
    };
    /** McsVisit */
    McsVisit: {
      /** Exposures */
      exposures: components["schemas"]["McsExposure"][];
    };
    /** ObslogUser */
    ObslogUser: {
      /** Id */
      id: number;
      /** Account Name */
      account_name: string;
    };
    /** PfsDesignDetail */
    PfsDesignDetail: {
      fits_meta: components["schemas"]["FitsMeta"];
      /**
       * Date Modified
       * Format: date-time
       */
      date_modified: string;
      design_data: components["schemas"]["DesignData"];
      photometry_data: components["schemas"]["PhotometryData"];
      guidestar_data: components["schemas"]["GuidestarData"];
    };
    /** PfsDesignEntry */
    PfsDesignEntry: {
      /** Id */
      id: string;
      /** Frameid */
      frameid: string;
      /** Name */
      name: string;
      /**
       * Date Modified
       * Format: date-time
       */
      date_modified: string;
      /** Ra */
      ra: number;
      /** Dec */
      dec: number;
      /** Arms */
      arms: string;
      /** Num Design Rows */
      num_design_rows: number;
      /** Num Photometry Rows */
      num_photometry_rows: number;
      /** Num Guidestar Rows */
      num_guidestar_rows: number;
      design_rows: components["schemas"]["DesignRows"];
    };
    /** PhotometryData */
    PhotometryData: {
      /** Fiberid */
      fiberId: number[];
      /** Fiberflux */
      fiberFlux: number[];
      /** Psfflux */
      psfFlux: number[];
      /** Totalflux */
      totalFlux: number[];
      /** Fiberfluxerr */
      fiberFluxErr: number[];
      /** Psffluxerr */
      psfFluxErr: number[];
      /** Totalfluxerr */
      totalFluxErr: number[];
      /** Filtername */
      filterName: string[];
    };
    /** Session */
    Session: {
      current_user?: components["schemas"]["CurrentUser"];
    };
    /** SessionCreateRequest */
    SessionCreateRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
    };
    /** SpsAnnotation */
    SpsAnnotation: {
      /** Data Flag */
      data_flag: number;
      /** Notes */
      notes: string;
      /** Annotation Id */
      annotation_id: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at?: string;
    };
    /** SpsExposure */
    SpsExposure: {
      /** Camera Id */
      camera_id: number;
      /** Exptime */
      exptime: number;
      /**
       * Exp Start
       * Format: date-time
       */
      exp_start: string;
      /**
       * Exp End
       * Format: date-time
       */
      exp_end: string;
      /** Annotation */
      annotation: components["schemas"]["SpsAnnotation"][];
    };
    /** SpsSequenceDetail */
    SpsSequenceDetail: {
      /** Visit Set Id */
      visit_set_id: number;
      /** Sequence Type */
      sequence_type?: string;
      /** Name */
      name?: string;
      /** Comments */
      comments?: string;
      /** Cmd Str */
      cmd_str?: string;
      status?: components["schemas"]["IicSequenceStatus"];
      /** Notes */
      notes: components["schemas"]["VisitSetNote"][];
    };
    /** SpsVisit */
    SpsVisit: {
      /** Exp Type */
      exp_type: string;
      /** Exposures */
      exposures: components["schemas"]["SpsExposure"][];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (Partial<string> & Partial<number>)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VisitDetail */
    VisitDetail: {
      /** Id */
      id: number;
      /** Description */
      description?: string;
      /**
       * Issued At
       * Format: date-time
       */
      issued_at?: string;
      /** Notes */
      notes: components["schemas"]["VisitNote"][];
      sps?: components["schemas"]["SpsVisit"];
      mcs?: components["schemas"]["McsVisit"];
      agc?: components["schemas"]["AgcVisit"];
      sps_sequence?: components["schemas"]["SpsSequenceDetail"];
    };
    /** VisitList */
    VisitList: {
      /** Visits */
      visits: components["schemas"]["VisitListEntry"][];
      /** Iic Sequence */
      iic_sequence: components["schemas"]["IicSequence"][];
      /** Count */
      count: number;
    };
    /** VisitListEntry */
    VisitListEntry: {
      /** Id */
      id: number;
      /** Description */
      description?: string;
      /**
       * Issued At
       * Format: date-time
       */
      issued_at?: string;
      /** Visit Set Id */
      visit_set_id?: number;
      /** N Sps Exposures */
      n_sps_exposures: number;
      /** N Mcs Exposures */
      n_mcs_exposures: number;
      /** N Agc Exposures */
      n_agc_exposures: number;
      /** Avg Exptime */
      avg_exptime?: number;
      /** Avg Azimuth */
      avg_azimuth?: number;
      /** Avg Altitude */
      avg_altitude?: number;
      /** Avg Ra */
      avg_ra?: number;
      /** Avg Dec */
      avg_dec?: number;
      /** Avg Insrot */
      avg_insrot?: number;
      /** Notes */
      notes: components["schemas"]["VisitNote"][];
    };
    /** VisitNote */
    VisitNote: {
      /** Id */
      id: number;
      /** User Id */
      user_id: number;
      /** Pfs Visit Id */
      pfs_visit_id: number;
      /** Body */
      body: string;
      user: components["schemas"]["ObslogUser"];
    };
    /** VisitNoteCreateRequest */
    VisitNoteCreateRequest: {
      /** Body */
      body: string;
    };
    /** VisitNoteCreateResponse */
    VisitNoteCreateResponse: {
      /** Id */
      id: number;
    };
    /** VisitNoteUpdateRequest */
    VisitNoteUpdateRequest: {
      /** Body */
      body: string;
    };
    /** VisitRankResponse */
    VisitRankResponse: {
      /** Rank */
      rank?: number;
    };
    /** VisitSetNote */
    VisitSetNote: {
      /** Id */
      id: number;
      /** User Id */
      user_id: number;
      /** Iic Sequence Id */
      iic_sequence_id: number;
      /** Body */
      body: string;
      user: components["schemas"]["ObslogUser"];
    };
    /** VisitSetNoteCreateRequest */
    VisitSetNoteCreateRequest: {
      /** Body */
      body: string;
    };
    /** VisitSetNoteCreateResponse */
    VisitSetNoteCreateResponse: {
      /** Id */
      id: number;
    };
    /** VisitSetNoteUpdateRequest */
    VisitSetNoteUpdateRequest: {
      /** Body */
      body: string;
    };
  };
}

export interface operations {
  show_session: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
    };
  };
  create_session: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Session"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SessionCreateRequest"];
      };
    };
  };
  destroy_session: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  index_visits: {
    parameters: {
      query: {
        sql?: string;
        offset?: number;
        limit?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VisitList"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_visit: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VisitDetail"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  visit_rank: {
    parameters: {
      path: {
        id: number;
      };
      query: {
        sql?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VisitRankResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_visit_csv: {
    parameters: {
      query: {
        sql?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_visit_note: {
    parameters: {
      path: {
        visit_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VisitNoteCreateResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VisitNoteCreateRequest"];
      };
    };
  };
  update_visit_note: {
    parameters: {
      path: {
        visit_id: number;
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VisitNoteUpdateRequest"];
      };
    };
  };
  destroy_visit_note: {
    parameters: {
      path: {
        visit_id: number;
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_visit_set_note: {
    parameters: {
      path: {
        visit_set_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["VisitSetNoteCreateResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VisitSetNoteCreateRequest"];
      };
    };
  };
  update_visit_set_note: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["VisitSetNoteUpdateRequest"];
      };
    };
  };
  destroy_visit_set_note: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_mcs_data_chart: {
    parameters: {
      path: {
        frame_id: number;
      };
      query: {
        width?: number;
        height?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_pfs_design: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PfsDesignEntry"][];
        };
      };
    };
  };
  pfs_design_chart: {
    parameters: {
      query: {
        id_hex: string[];
        date?: string;
        return_error?: boolean;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_design: {
    parameters: {
      path: {
        id_hex: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_design: {
    parameters: {
      path: {
        id_hex: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["PfsDesignDetail"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_sps_fits: {
    parameters: {
      path: {
        visit_id: number;
        camera_id: number;
      };
      query: {
        type?: components["schemas"]["FitsType"];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_sps_fits_preview: {
    parameters: {
      path: {
        visit_id: number;
        camera_id: number;
      };
      query: {
        width?: number;
        height?: number;
        type?: components["schemas"]["FitsType"];
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_agc_fits: {
    parameters: {
      path: {
        visit_id: number;
        exposure_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_mcs_fits: {
    parameters: {
      path: {
        visit_id: number;
        frame_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_mcs_fits_preview: {
    parameters: {
      path: {
        visit_id: number;
        frame_id: number;
      };
      query: {
        width?: number;
        height?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_agc_fits_preview: {
    parameters: {
      path: {
        visit_id: number;
        exposure_id: number;
        hdu_index: number;
      };
      query: {
        width?: number;
        height?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  show_fits_meta: {
    parameters: {
      path: {
        visit_id: number;
        exposure_type: "sps" | "mcs" | "agc";
        fits_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["FitsMeta"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_attachment: {
    parameters: {
      query: {
        start?: number;
        per_page?: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["AttachmentList"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_attachment: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CreateAttachmentResponse"];
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_attachment_api_attachments_post"];
      };
    };
  };
  show_attachment: {
    parameters: {
      path: {
        account_name: string;
        file_id: number;
      };
      query: {
        filename?: string;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  destroy_attachment: {
    parameters: {
      path: {
        file_id: number;
      };
    };
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz: {
    responses: {
      /** Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
    };
  };
}

export interface external {}
