/**
 * Main API slice - re-exports from enhanced API
 *
 * This file provides a single entry point for all API-related imports.
 * The actual endpoints are generated by @rtk-query/codegen-openapi
 * and enhanced with cache tags in enhancedApi.ts.
 */
export { enhancedApi as api } from "./enhancedApi";
export * from "./enhancedApi";

