/**
 * Main API slice - re-exports from generated API
 * 
 * This file provides a single entry point for all API-related imports.
 * The actual endpoints are generated by @rtk-query/codegen-openapi.
 */
export { generatedApi as api } from "./generatedApi";
export * from "./generatedApi";
