export type Styles = {
  armCell: string;
  badge: string;
  cameraGrid: string;
  cameraId: string;
  cameraItem: string;
  cameraLink: string;
  commandCode: string;
  commandLabel: string;
  commandSection: string;
  commentsLabel: string;
  commentsSection: string;
  commentsText: string;
  content: string;
  dataTable: string;
  downloadButton: string;
  emptyCell: string;
  exposureCard: string;
  exposureCardActions: string;
  exposureCardHeader: string;
  exposureCardImages: string;
  exposureCardInfo: string;
  exposureInfo: string;
  exposureList: string;
  exposureTable: string;
  exptime: string;
  header: string;
  headerError: string;
  headerHint: string;
  headerIcon: string;
  headerItem: string;
  headerLabel: string;
  headerLoading: string;
  headerPanel: string;
  headerPanelContent: string;
  headerPanelPlaceholder: string;
  headerPanelTitle: string;
  headerPlaceholder: string;
  headerValue: string;
  infoGrid: string;
  infoLabel: string;
  infoRow: string;
  infoValue: string;
  inspector: string;
  noteBody: string;
  noteItem: string;
  notesLabel: string;
  notesSection: string;
  noteUser: string;
  pagination: string;
  previewActions: string;
  previewCell: string;
  previewContainer: string;
  previewInfo: string;
  scrollable: string;
  selected: string;
  settings: string;
  settingsGroup: string;
  settingsLabel: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
