export type Styles = {
  colDate: string;
  colDescription: string;
  colExposures: string;
  colExptime: string;
  colId: string;
  colNotes: string;
  colTime: string;
  columnSelector: string;
  columnsRow: string;
  command: string;
  comments: string;
  content: string;
  empty: string;
  error: string;
  errorInput: string;
  exposureAgc: string;
  exposureMcs: string;
  exposureMcsAgc: string;
  exposureMixed: string;
  exposureNone: string;
  exposureSps: string;
  exposureSpsAgc: string;
  exposureSpsMcs: string;
  footer: string;
  iicSequence: string;
  info: string;
  loading: string;
  noSequence: string;
  notesBadge: string;
  pageInfo: string;
  pageRange: string;
  pageTotal: string;
  pagination: string;
  paginationBottom: string;
  paginationButton: string;
  paginationTop: string;
  searchBox: string;
  searchError: string;
  searchInput: string;
  selected: string;
  sequenceGroup: string;
  sequenceId: string;
  sequenceName: string;
  sequenceType: string;
  sequenceTypeArc: string;
  sequenceTypeFlat: string;
  sequenceTypeScience: string;
  sqlInput: string;
  status: string;
  statusError: string;
  statusOk: string;
  title: string;
  toolbar: string;
  toolbarActions: string;
  toolbarButton: string;
  visitGroup: string;
  visitGroupSelected: string;
  visitList: string;
  visitTable: string;
};

export type ClassNames = keyof Styles;

declare const styles: Styles;

export default styles;
