version: "3.7"
services:
  db:
    restart: always
    image: postgres:12
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
